config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # This place is used for path to pages.
  root 'pages#index'

  get '/index', to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  resources :polls
  resources :poll_members
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :poll
  has_many :poll_members, dependent: :nullify
  validates :title, presence: true
end

app/models/poll.rb
# frozen_string_literal: true

class Poll < ApplicationRecord
  belongs_to :user
  has_many :options
  has_many :poll_members
  has_many :invited_users, through: :poll_members, source: :user

  validates :title, presence: true
  validates :description, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true

  accepts_nested_attributes_for :options
end

app/models/poll_member.rb
class PollMember < ApplicationRecord
  belongs_to :user
  belongs_to :poll
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :poll_members, dependent: :destroy
  has_many :invite_polls, through: :poll_members, source: :poll
  has_many :polls

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 40 }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id]) if session[:current_user_id]
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
end

app/controllers/poll_members_controller.rb
# frozen_string_literal: true

class PollMembersController < ApplicationController
  def create
    user = User.find_by!(email: permitted_params[:email])
    poll = Poll.find(permitted_params[:poll_id])

    user.invite_polls << poll

    flash[:success] = 'User invited!'
    redirect_to poll_path(poll)
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Invitation error'
    redirect_to polls_path
  end

  private

  def permitted_params
    {
      email: params[:email].strip,
      poll_id: params[:poll_id]
    }
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path, alert: 'Poll Not Found!'
  end
  before_action :check_auth
  # before_action, only: [:edit, ]
  def index
    @polls = current_user.polls
  end

  def new
    @poll = Poll.new
  end

  def show
    @poll = Poll.find(params[:id])
    @poll_member = @poll.poll_members.build
  end

  def create
    @poll = current_user.polls.build(poll_params)
    if @poll.save
      flash[:success] = 'Poll has created successfuly!'
      redirect_to poll_path(@poll)
    else
      render 'new'
    end
  end

  def edit
    @poll = Poll.find(params[:id])
  end

  def update
    @poll = Poll.find(params[:id])
    if @poll.update(poll_params)
      flash[:success] = 'Poll was successfuly updated!'
      redirect_to poll_path
    else
      render 'edit'
    end
  end

  def destroy
    Poll.find(params[:id]).destroy
    flash[:success] = 'Poll has been destroyed!'
    redirect_to root_path
  end

  private

  def check_auth
    return if current_user

    flash[:info] = 'Please log in'
    redirect_to login_path
  end

  def poll_params
    params.require(:poll).permit(:title, :description, :start_at, :end_at)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = authenticate(session_params)
    if user
      session[:current_user_id] = user.id
      flash[:success] = 'Log in successful!'
      redirect_to root_url
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:current_user_id)
    flash[:success] = 'You have successfully logged out.'
    @current_user = nil
    redirect_to root_url
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

  def authenticate(params)
    user = User.find_by(email: params[:email])
    user&.authenticate(params[:password])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      WelcomeMailer.welcome(@user).deliver_later
      flash[:success] = 'Registration Successful!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_footer.html.haml
%footer.footer.mt-auto.py-3.bg-light
  .container
    %span.text-muted Alexey Leskov 2021

app/views/layouts/_header.html.haml
%body
  %header.p-3.bg-dark.text-white
    .container
      = link_to "Fun Poll", root_path, id: "logo"
      .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
        %a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none{:href => "/"}
          %svg.bi.me-2{:height => "32", :width => "40"}
            %use{"xlink:href" => "#bootstrap"}
        %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
          %li
            %a.nav-link.px-2.text-white{:href => "/"} Home
          %li
            %a.nav-link.px-2.text-white{:href => "/about"} About
        .text-end
          - if current_user
            = link_to "List of polls", polls_path, class: 'btn.btn-outline-light.me-2'
            = link_to "New Poll", new_poll_path, class: 'btn.btn-outline-light.me-2'
            = link_to "Logout", logout_path, :method => 'delete', class: 'btn.btn-outline-light.me-2'
          -else
            = link_to "Login", login_path, class: 'btn.btn-outline-light.me-2'
            = link_to "Sign-up", signup_path, class: 'btn btn-warning'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FunPoll
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css", :integrity => "sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")

      = yield
      = render 'layouts/footer'

app/views/pages/about.html.haml
%html_safe
%head
%title About|FunPoll 
%body
%h1 About us
%p Here must be more information about FunPoll application

app/views/pages/index.html.haml
%html
%head
%title FunPoll
%body
%h1 Welcome to Fun Poll Application!
%p
This is the home page

app/views/polls/_poll.html.haml
%li
  = link_to poll.title, poll
  | #{link_to "Edit", edit_poll_path(poll)} | #{link_to "Delete", poll, method: :delete, data: {confirm: "Are you sure?" }}

app/views/polls/edit.html.haml
%h1 Update your Poll!
.row
  .col-md-6.col-md-offset-3
    = form_for @poll, local: true do |f|
      = f.label :title
      = f.text_field :title
      - @poll.errors.full_messages_for(:title).each do |message|
        %div= message
    
      = f.label :description
      = f.text_field :description
      - @poll.errors.full_messages_for(:description).each do |message|
        %div= message

      = f.label :start_at
      = f.datetime_field :start_at
      - @poll.errors.full_messages_for(:start_at).each do |message|
        %div= message

      = f.label :end_at
      = f.datetime_field :end_at
      - @poll.errors.full_messages_for(:end_at).each do |message|
        %div= message

      = f.submit "Update my poll", class: "btn btn-primary"

app/views/polls/index.html.haml
%body
%p List of Polls
%ul
  = render @polls

app/views/polls/new.html.haml
%h1 Create your Poll!
.row
  .col-md-6.col-md-offset-3
    = form_for @poll, local: true do |f|
      = f.label :title
      = f.text_field :title
      - @poll.errors.full_messages_for(:title).each do |message|
        %div= message
    
      = f.label :description
      = f.text_field :description
      - @poll.errors.full_messages_for(:description).each do |message|
        %div= message

      = f.label :start_at
      = f.datetime_field :start_at
      - @poll.errors.full_messages_for(:start_at).each do |message|
        %div= message

      = f.label :end_at
      = f.datetime_field :end_at
      - @poll.errors.full_messages_for(:end_at).each do |message|
        %div= message

      = f.submit "Create my poll", class: "btn btn-primary"

app/views/polls/show.html.haml
.row
  %aside.col-md-4
    %section.poll_info
      %h1
        = @poll.title
      %p 
        = @poll.description
      %p
        Starts at:
        = @poll.start_at 
      %p
        Ends at:
        = @poll.end_at
      %p
        = link_to "Edit", edit_poll_path, class: 'btn btn-warning'
        = link_to "Delete Poll", @poll, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn.btn-outline-light.me-2'

      %p
        = @poll.invited_users.pluck(:email).join(', ')

      %p Invite users to your poll!

.row
  .col-md-6.col-md-offset-3
    = form_tag('/poll_members') do
      = hidden_field_tag :poll_id, @poll.id
      = label_tag :email, "Email of user"
      = email_field_tag :email, '', placeholder: User.human_attribute_name(:email)
      = submit_tag "invite user", class: "btn btn-primary"

app/views/users/new.html.haml
%h1 Sign up
.row
  .col-md-6.col-md-offset-3
    = form_with model: @user, local: true do |f|
      = f.label :name
      = f.text_field :name
      - @user.errors.full_messages_for(:name).each do |message|
        %div= message
    
      = f.label :email
      = f.email_field :email
      - @user.errors.full_messages_for(:email).each do |message|
        %div= message

      = f.label :password
      = f.password_field :password
      - @user.errors.full_messages_for(:password).each do |message|
        %div= message

      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation
      - @user.errors.full_messages_for(:password).each do |message|
        %div= message

      = f.submit "Create my account", class: "btn btn-primary"